/***************************************************************************//**
 * @file win32_pfx.hpp
 * @author StoneyDSP (nathanjhood@googlemail.com)
 *
 * @brief Contains pointers to named resources with external linkage, so that
 * their respective contents can be defined elsewhere. Also contains definitions
 * of functions that provide access to these specifically-named resources, which
 * necessitates external linkage.
 *
 * @version 1.0.0-init
 * @date 2023-08-24
 *
 * @copyright This file was generated by using Vector-of-Bool's excellent
 * 'CMakeRC' resource compiler script from CMake's template resources for
 * Windows. The results have been given minimal tweaks - mostly just text
 * formatting - to provide a similar interface to the rest of the project's
 * codebase. Please see 'cmrc.hpp' and Kitware.org for respective license
 * information.
 *
 ******************************************************************************/
#pragma once
/**
 * @brief Contains definitions of functions that provide access to
 * specifically-named resources, which necessitates external linkage.
 */
#define _WIN32_RESOURCE_KEY_PFX_H_

#include <map>
#include <utility>

#include "../cmrc.hpp"

namespace CMakeRC
{
/**
 * @namespace 'CMakeRC::Key'
 *
 * @brief The 'CMakeRC::Key' namespace. This namespace contains definitions and
 * declarations of keys that have been compiled into binary bits. It also
 * contains functions to provide a handle to those keys.
 *
 */
namespace Key
{
namespace Windows_TemporaryKey
{
/** @brief Pointer to the beginning of 'Windows_TemporaryKey_pfx_array'. */
extern RCRESOURCEPTR const Windows_TemporaryKey_pfx_begin;
/** @brief Pointer to the end of 'Windows_TemporaryKey_pfx_array'. */
extern RCRESOURCEPTR const Windows_TemporaryKey_pfx_end;
} // namespace Windows_TemporaryKey

namespace
{
const IDXRES& GetRootIndex();
} // namespace

FSEMBEDDED GetFileSystem();
} // namespace Key
} // namespace CMakeRC
