/***************************************************************************//**
 * @file win32_Windows_TemporaryKey_pfx.hpp
 * @author StoneyDSP (nathanjhood@googlemail.com)
 *
 * @brief Contains a default definition of 'Windows_TemporaryKey_pfx_array' (see
 * 'copyright' section).
 *
 * @version 1.0.0-init
 * @date 2023-08-24
 *
 * @copyright This file was generated by using Vector-of-Bool's excellent
 * 'CMakeRC' resource compiler script from CMake's template resources for
 * Windows. The results have been given minimal tweaks - mostly just text
 * formatting - to provide a similar interface to the rest of the project's
 * codebase. Please see 'cmrc.hpp' and Kitware.org for respective license
 * information.
 *
 * @see 'Windows_TemporaryKey.pfx'
 *
 ******************************************************************************/
#pragma once
/**
 * @brief Contains a default declaration of 'Windows_TemporaryKey_pfx_array'
 * (see 'copyright' section).
 *
 */
#define _WIN32_RESOURCE_KEY_WINDOWS_TEMPORARY_KEY_PFX_HPP_

namespace
{
/** @brief An array of bytes representing 'Windows_TemporaryKey.pfx'. */
RCRESOURCE Windows_TemporaryKey_pfx_array[2561];
} // namespace

namespace CMakeRC
{
namespace Key
{
/**
 * @namespace 'CMakeRC::Key::Windows_TemporaryKey'
 *
 * @brief The 'Windows_TemporaryKey' namespace. Contains declarations and definitions
 * of binary-compiled 'Windows_TemporaryKey.pfx' for interacting with Win32 API.
 *
 */
namespace Windows_TemporaryKey
{
/** @brief Pointer to the beginning of 'Windows_TemporaryKey_pfx_array'. */
extern RCRESOURCEPTR const Windows_TemporaryKey_pfx_begin;
/** @brief Pointer to the end of 'Windows_TemporaryKey_pfx_array'. */
extern RCRESOURCEPTR const Windows_TemporaryKey_pfx_end;
} // namespace Windows_TemporaryKey
} // namespace CMakeRC::Key
}
