/***************************************************************************//**
 * @file win32_StoreLogo_png.hpp
 * @author StoneyDSP (nathanjhood@googlemail.com)
 *
 * @brief Contains a default definition of 'StoreLogo_png_array' (see
 * 'copyright' section).
 *
 * @version 1.0.0-init
 * @date 2023-08-24
 *
 * @copyright This file was generated by using Vector-of-Bool's excellent
 * 'CMakeRC' resource compiler script from CMake's template resources for
 * Windows. The results have been given minimal tweaks - mostly just text
 * formatting - to provide a similar interface to the rest of the project's
 * codebase. Please see 'cmrc.hpp' and Kitware.org for respective license
 * information.
 *
 * @see 'StoreLogo.png'
 *
 ******************************************************************************/
#pragma once
/**
 * @brief Contains a default definition of 'StoreLogo_png_array' (see
 * 'copyright' section).
 */
#define _WIN32_RESOURCE_IMG_STORE_LOGO_PNG_H_

namespace
{
RCRESOURCE StoreLogo_png_array[228];
}

namespace CMakeRC
{
namespace Img
{
/**
 * @namespace 'CMakeRC::Key::StoreLogo'
 *
 * @brief The 'StoreLogo' namespace. Contains declarations and definitions
 * of binary-compiled 'StoreLogo.png' for interacting with Win32 API.
 *
 */
namespace StoreLogo
{
/** @brief Pointer to the beginning of 'StoreLogo_png_array'. */
extern RCRESOURCEPTR const StoreLogo_png_begin;
/** @brief Pointer to the end of 'StoreLogo_png_array'. */
extern RCRESOURCEPTR const StoreLogo_png_end;
} // namespace StoreLogo
} // namespace Img
} // namespace CMakeRC
