/***************************************************************************//**
 * @file win32_SmallLogo44x44_png.hpp
 * @author StoneyDSP (nathanjhood@googlemail.com)
 *
 * @brief Contains a default declaration of 'SmallLogo44x44_png_array' (see
 * 'copyright' section).
 *
 * @version 1.0.0-init
 * @date 2023-08-24
 *
 * @copyright This file was generated by using Vector-of-Bool's excellent
 * 'CMakeRC' resource compiler script from CMake's template resources for
 * Windows. The results have been given minimal tweaks - mostly just text
 * formatting - to provide a similar interface to the rest of the project's
 * codebase. Please see 'cmrc.hpp' and Kitware.org for respective license
 * information.
 *
 * @see 'SmallLogo44x44.png'
 *
 ******************************************************************************/
#pragma once

/**
 * @brief Contains a default declaration of 'SmallLogo_png_array' (see
 * 'copyright' section).
 *
 */
#define _WIN32_RESOURCE_IMG_SMALL_LOGO_44X44_PNG_H_

namespace
{
/** @brief An array of bytes representing 'SmallLogo44x44.png'. */
RCRESOURCE SmallLogo44x44_png_array[266];
} // namespace

namespace CMakeRC::Img
{
/**
 * @namespace CMakeRC::Img::SmallLogo44x44
 *
 * @brief The 'SmallLogo44x44' namespace. Contains declarations and definitions
 * of binary-compiled 'SmallLogo44x44.png' for interacting with Win32 API.
 *
 */
namespace SmallLogo44x44
{
/** @brief Pointer to the beginning of 'SmallLogo44x44_png_array'. */
extern RCRESOURCEPTR const SmallLogo44x44_png_begin;
/** @brief Pointer to the end of 'SmallLogo44x44_png_array'. */
extern RCRESOURCEPTR const SmallLogo44x44_png_end;
} // namespace SmallLogo44x44
} // namespace CMakeRC::Img
