/***************************************************************************//**
 * @file win32_Logo_png.hpp
 * @author StoneyDSP (nathanjhood@googlemail.com)
 *
 * @brief Contains a default declaration of 'Logo_png_array' (see
 * 'copyright' section).
 *
 * @version 1.0.0
 * @date 2023-08-24
 *
 * @copyright This file was generated by using Vector-of-Bool's excellent
 * 'CMakeRC' resource compiler script from CMake's template resources for
 * Windows. The results have been given minimal tweaks - mostly just text
 * formatting - to provide a similar interface to the rest of the project's
 * codebase. Please see 'cmrc.hpp' and Kitware.org for respective license
 * information.
 *
 * @see 'Logo.png'
 *
 ******************************************************************************/
#pragma once
/**
 * @brief Contains a default declaration of 'Logo_png_array' (see
 * 'copyright' section).
 *
 */
#define _WIN32_RESOURCE_IMG_LOGO_PNG_H_

namespace
{
/** @brief An array of bytes representing 'Logo.png'. */
RCRESOURCE Logo_png_array[489];
} // namespace

namespace CMakeRC::Img
{
/**
 * @namespace 'CMakeRC::Img::Logo'
 *
 * @brief The 'Logo' namespace. Contains declarations and definitions
 * of binary-compiled 'Logo.png' for interacting with Win32 API.
 *
 */
namespace Logo
{
/** @brief Pointer to the beginning of 'Logo_png_array'. */
extern RCRESOURCEPTR const Logo_png_begin;
/** @brief Pointer to the end of 'Logo_png_array'. */
extern RCRESOURCEPTR const Logo_png_end;
} // namespace Logo
} // namespace CMakeRC::Img
