/***************************************************************************//**
 * @file win32_SmallLogo_png.cpp
 * @author StoneyDSP (nathanjhood@googlemail.com)
 *
 * @brief Contains a default definition of 'SmallLogo_png_array' (see
 * 'copyright' section).
 *
 * @version 1.0.0
 * @date 2023-08-24
 *
 * @copyright This file was generated by using Vector-of-Bool's excellent
 * 'CMakeRC' resource compiler script from CMake's template resources for
 * Windows. The results have been given minimal tweaks - mostly just text
 * formatting - to provide a similar interface to the rest of the project's
 * codebase. Please see 'cmrc.hpp' and Kitware.org for respective license
 * information.
 *
 * @see 'SmallLogo.png'
 *
 ******************************************************************************/

#include "win32_SmallLogo_png.hpp"

namespace
{
/**
 * @brief An array of bytes representing "SmallLogo.png".
 *
 * @see 'SmallLogo.png'
 *
 */
const char SmallLogo_png_array[168] = {
    '\x89', '\x50', '\x4e', '\x47', '\x0d',
    '\x0a', '\x1a', '\x0a', '\x00', '\x00',
    '\x00', '\x0d', '\x49', '\x48', '\x44',
    '\x52', '\x00', '\x00', '\x00', '\x1e',
    '\x00', '\x00', '\x00', '\x1e', '\x08',
    '\x04', '\x00', '\x00', '\x00', '\x91',
    '\x39', '\x66', '\x29', '\x00', '\x00',
    '\x00', '\x6e', '\x49', '\x44', '\x41',
    '\x54', '\x78', '\xda', '\xd5', '\xd4',
    '\xc9', '\x19', '\x43', '\x21', '\x08',
    '\x06', '\x40', '\x0a', '\xa0', '\xff',
    '\x0b', '\xc5', '\xa4', '\x34', '\x53',
    '\x80', '\x93', '\xbc', '\xe5', '\x3f',
    '\x09', '\x37', '\x3f', '\xc7', '\x5d',
    '\xea', '\xe8', '\x58', '\x9f', '\x67',
    '\xb9', '\xe3', '\x59', '\x7d', '\x39',
    '\x49', '\xaf', '\x11', '\x1e', '\x70',
    '\xd3', '\xd9', '\x71', '\x9b', '\x83',
    '\xf6', '\x86', '\xab', '\xc8', '\x41',
    '\xab', '\x80', '\xc9', '\x41', '\x89',
    '\xc1', '\x49', '\x8d', '\xcd', '\xd1',
    '\x02', '\x8c', '\xce', '\xa2', '\xc6',
    '\xe2', '\xa0', '\xc6', '\xe2', '\xa0',
    '\xc6', '\xe2', '\xa2', '\x39', '\xce',
    '\x97', '\x9d', '\x1f', '\x58', '\x7e',
    '\x55', '\xf1', '\x23', '\x09', '\x9e',
    '\xa7', '\x29', '\x78', '\xf8', '\x25',
    '\xf3', '\x62', '\x90', '\x97', '\xa1',
    '\xbc', '\x00', '\x3e', '\xcb', '\x3a',
    '\x39', '\xbe', '\xdd', '\x15', '\xb8',
    '\x38', '\x93', '\x10', '\x74', '\x76',
    '\x00', '\x00', '\x00', '\x00', '\x49',
    '\x45', '\x4e', '\x44', '\xae', '\x42',
    '\x60', '\x82', 0 };
}

namespace CMakeRC::Img
{
namespace SmallLogo
{
extern const char* const SmallLogo_png_begin = ::SmallLogo_png_array;
extern const char* const SmallLogo_png_end = ::SmallLogo_png_array + 167;
} // namespace SmallLogo
} // namespace CMakeRC::Img
