/***************************************************************************//**
 * @file win32_SmallLogo44x44_png.cpp
 * @author StoneyDSP (nathanjhood@googlemail.com)
 *
 * @brief Contains a default definition of 'SmallLogo44x44_png_array' (see
 * 'copyright' section).
 *
 * @version 1.0.0-init
 * @date 2023-08-24
 *
 * @copyright This file was generated by using Vector-of-Bool's excellent
 * 'CMakeRC' resource compiler script from CMake's template resources for
 * Windows. The results have been given minimal tweaks - mostly just text
 * formatting - to provide a similar interface to the rest of the project's
 * codebase. Please see 'cmrc.hpp' and Kitware.org for respective license
 * information.
 *
 * @see 'SmallLogo44x44.png'
 *
 ******************************************************************************/

#include "win32_SmallLogo44x44_png.hpp"

namespace
{
/** @brief An array of bytes representing 'SmallLogo44x44.png'. */
RCRESOURCE SmallLogo44x44_png_array[266] = {
    '\x89', '\x50', '\x4e', '\x47', '\x0d',
    '\x0a', '\x1a', '\x0a', '\x00', '\x00',
    '\x00', '\x0d', '\x49', '\x48', '\x44',
    '\x52', '\x00', '\x00', '\x00', '\x2c',
    '\x00', '\x00', '\x00', '\x2c', '\x08',
    '\x04', '\x00', '\x00', '\x00', '\xb4',
    '\x8d', '\x92', '\x8a', '\x00', '\x00',
    '\x00', '\xd0', '\x49', '\x44', '\x41',
    '\x54', '\x78', '\xda', '\xed', '\xd7',
    '\xc5', '\x01', '\x83', '\x30', '\x00',
    '\x85', '\x61', '\x74', '\xe6', '\xfa',
    '\x20', '\xd9', '\x21', '\x8c', '\x40',
    '\xb2', '\x40', '\x67', '\xa1', '\x23',
    '\x60', '\xc7', '\xd8', '\x5f', '\x7b',
    '\x37', '\xdc', '\x3f', '\x88', '\x59',
    '\x75', '\x4c', '\xc1', '\xe4', '\xe7',
    '\xff', '\xcd', '\x11', '\xec', '\xa6',
    '\xf1', '\xee', '\x4e', '\xdf', '\xcf',
    '\xeb', '\xdb', '\x53', '\x02', '\x76',
    '\xaf', '\xf5', '\xa2', '\x35', '\x7d',
    '\xf5', '\xe5', '\x64', '\x7a', '\x6f',
    '\x77', '\x25', '\x84', '\xc7', '\x87',
    '\xb7', '\x48', '\x03', '\xbb', '\xae',
    '\x8f', '\x08', '\xf6', '\x67', '\xd3',
    '\x23', '\x0d', '\xec', '\xb3', '\xf7',
    '\xe7', '\x04', '\x5c', '\x55', '\x48',
    '\x03', '\x5b', '\x55', '\x19', '\x18',
    '\x69', '\x60', '\xb3', '\x30', '\xd0',
    '\xc0', '\x02', '\x9c', '\xa1', '\x91',
    '\x05', '\x18', '\x68', '\x60', '\x01',
    '\x8e', '\x68', '\x64', '\x11', '\x06',
    '\x1a', '\x58', '\x84', '\x63', '\x1a',
    '\x58', '\x86', '\x81', '\x06', '\x16',
    '\x60', '\xa0', '\x33', '\x2c', '\xc0',
    '\x40', '\xe7', '\x58', '\x86', '\x89',
    '\x86', '\xbc', '\x02', '\x70', '\x96',
    '\x76', '\x83', '\x1b', '\x32', '\x2c',
    '\xc3', '\x79', '\x7a', '\x47', '\x57',
    '\x3c', '\x66', '\xf5', '\xb0', '\x38',
    '\x2a', '\xf4', '\x89', '\xa7', '\xcf',
    '\x6e', '\xcc', '\x32', '\xad', '\x2f',
    '\xd2', '\xfa', '\x4a', '\x48', '\x5f',
    '\x6d', '\x02', '\x0b', '\xb4', '\xbe',
    '\x69', '\xd2', '\x37', '\xa6', '\xea',
    '\xe6', '\x1f', '\x59', '\xa0', '\x85',
    '\x5d', '\x2c', '\x59', '\xa7', '\x50',
    '\xd6', '\x8d', '\x95', '\x75', '\xbc',
    '\x95', '\x43', '\x05', '\xfd', '\xe0',
    '\xe6', '\x98', '\xf6', '\x69', '\x01',
    '\xcc', '\x16', '\x2c', '\x52', '\x4a',
    '\x60', '\x27', '\x59', '\x00', '\x00',
    '\x00', '\x00', '\x49', '\x45', '\x4e',
    '\x44', '\xae', '\x42', '\x60', '\x82',
    0 };
}

namespace CMakeRC::Img
{
namespace SmallLogo44x44
{
extern RCRESOURCEPTR const SmallLogo44x44_png_begin = ::SmallLogo44x44_png_array;
extern RCRESOURCEPTR const SmallLogo44x44_png_end = ::SmallLogo44x44_png_array + 265;
} // namespace SmallLogo44x44
} // namespace CMakeRC::Img
