.TH "anonymous_namespace{win32_SmallLogo_png.cpp}" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
anonymous_namespace{win32_SmallLogo_png.cpp}
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBSmallLogo_png_array\fP [168]"
.br
.RI "An array of bytes representing 'SmallLogo\&.png'\&. "
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char anonymous_namespace{win32_SmallLogo_png\&.cpp}::SmallLogo_png_array[168]"

.PP
An array of bytes representing 'SmallLogo\&.png'\&. 
.PP
\fBSee also\fP
.RS 4
'SmallLogo\&.png' 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
