.TH "anonymous_namespace{win32_StoreLogo_png.cpp}" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
anonymous_namespace{win32_StoreLogo_png.cpp}
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBRCRESOURCE\fP \fBStoreLogo_png_array\fP [228]"
.br
.RI "An array of bytes representing 'StoreLogo\&.png'\&. "
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBRCRESOURCE\fP anonymous_namespace{win32_StoreLogo_png\&.cpp}::StoreLogo_png_array[228]"

.PP
An array of bytes representing 'StoreLogo\&.png'\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
