.TH "anonymous_namespace{win32_SmallLogo44x44_png.cpp}" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
anonymous_namespace{win32_SmallLogo44x44_png.cpp}
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBRCRESOURCE\fP \fBSmallLogo44x44_png_array\fP [266]"
.br
.RI "An array of bytes representing 'SmallLogo44x44\&.png'\&. "
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBRCRESOURCE\fP anonymous_namespace{win32_SmallLogo44x44_png\&.cpp}::SmallLogo44x44_png_array[266]"

.PP
An array of bytes representing 'SmallLogo44x44\&.png'\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
