.TH "anonymous_namespace{win32_SplashScreen_png.cpp}" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
anonymous_namespace{win32_SplashScreen_png.cpp}
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBRCRESOURCE\fP \fBSplashScreen_png_array\fP [910]"
.br
.RI "An array of bytes representing 'SplashScreen\&.png'\&. "
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBRCRESOURCE\fP anonymous_namespace{win32_SplashScreen_png\&.cpp}::SplashScreen_png_array[910]"

.PP
An array of bytes representing 'SplashScreen\&.png'\&. 
.PP
\fBSee also\fP
.RS 4
'SplashScreen\&.png' 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
