.TH "anonymous_namespace{win32_Windows_TemporaryKey_pfx.cpp}" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
anonymous_namespace{win32_Windows_TemporaryKey_pfx.cpp}
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBRCRESOURCE\fP \fBWindows_TemporaryKey_pfx_array\fP [2561]"
.br
.RI "An array of bytes representing 'Windows_TemporaryKey\&.pfx'\&. "
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBRCRESOURCE\fP anonymous_namespace{win32_Windows_TemporaryKey_pfx\&.cpp}::Windows_TemporaryKey_pfx_array[2561]"

.PP
An array of bytes representing 'Windows_TemporaryKey\&.pfx'\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
