.TH "anonymous_namespace{win32_StoreLogo_png.hpp}" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
anonymous_namespace{win32_StoreLogo_png.hpp}
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBRCRESOURCE\fP \fBStoreLogo_png_array\fP [228]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBRCRESOURCE\fP anonymous_namespace{win32_StoreLogo_png\&.hpp}::StoreLogo_png_array[228]"

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
