.TH "include/CxxWin/modules/Win32_resource/key Directory Reference" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_resource/key Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBwin32_pfx\&.cpp\fP"
.br
.RI "Contains pointers to named resources with external linkage, so that their respective contents can be defined elsewhere\&. Also contains definitions of functions that provide access to these specifically-named resources, which necessitates external linkage\&. "
.ti -1c
.RI "file \fBwin32_pfx\&.hpp\fP"
.br
.RI "Contains pointers to named resources with external linkage, so that their respective contents can be defined elsewhere\&. Also contains definitions of functions that provide access to these specifically-named resources, which necessitates external linkage\&. "
.ti -1c
.RI "file \fBwin32_Windows_TemporaryKey_pfx\&.cpp\fP"
.br
.RI "Contains a default definition of 'Windows_TemporaryKey_pfx_array' (see 'copyright' section)\&. "
.ti -1c
.RI "file \fBwin32_Windows_TemporaryKey_pfx\&.hpp\fP"
.br
.RI "Contains a default definition of 'Windows_TemporaryKey_pfx_array' (see 'copyright' section)\&. "
.in -1c
