.TH "include/CxxWin/modules/Win32_core/window Directory Reference" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_core/window Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBwin32_BaseWindow\&.hpp\fP"
.br
.RI "Contains the '\fBBaseWindow\fP' interface\&. "
.ti -1c
.RI "file \fBwin32_DPIScale\&.cpp\fP"
.br
.RI "Contains the '\fBDPIScale\fP' class\&. "
.ti -1c
.RI "file \fBwin32_DPIScale\&.hpp\fP"
.br
.RI "Contains the '\fBDPIScale\fP' class\&. "
.ti -1c
.RI "file \fBwin32_MainWindow\&.cpp\fP"
.br
.RI "Contains a definition of the '\fBMainWindow\fP' class which inherits from the '\fBBaseWindow\fP' class\&. Inherit this '\fBMainWindow\fP' class for a basic window functionality\&. "
.ti -1c
.RI "file \fBwin32_MainWindow\&.hpp\fP"
.br
.RI "Contains a declaration of the '\fBMainWindow\fP' class which inherits from the '\fBBaseWindow\fP' class\&. Inherit this '\fBMainWindow\fP' class for a basic window functionality\&. "
.in -1c
