.TH "include/CxxWin/modules/Win32_resource/img Directory Reference" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_resource/img Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBwin32_ApplicationIcon_png\&.cpp\fP"
.br
.RI "Contains a default definition of 'ApplicationIcon_png_array' (see 'copyright' section)\&. "
.ti -1c
.RI "file \fBwin32_ApplicationIcon_png\&.hpp\fP"
.br
.RI "Contains a default declaration of 'ApplicationIcon_png_array' (see 'copyright' section)\&. "
.ti -1c
.RI "file \fBwin32_Logo_png\&.cpp\fP"
.br
.RI "Contains a default definition of 'Logo_png_array' (see 'copyright' section)\&. "
.ti -1c
.RI "file \fBwin32_Logo_png\&.hpp\fP"
.br
.RI "Contains a default declaration of 'Logo_png_array' (see 'copyright' section)\&. "
.ti -1c
.RI "file \fBwin32_png\&.cpp\fP"
.br
.RI "Contains pointers to named resources with external linkage, so that their respective contents can be defined elsewhere\&. Also contains definitions of functions that provide access to these specifically-named resources, which necessitates external linkage\&. "
.ti -1c
.RI "file \fBwin32_png\&.hpp\fP"
.br
.RI "Contains definitions of functions that provide access to specifically-named resources, which necessitates external linkage\&. "
.ti -1c
.RI "file \fBwin32_SmallLogo44x44_png\&.cpp\fP"
.br
.RI "Contains a default definition of 'SmallLogo44x44_png_array' (see 'copyright' section)\&. "
.ti -1c
.RI "file \fBwin32_SmallLogo44x44_png\&.hpp\fP"
.br
.RI "Contains a default declaration of 'SmallLogo44x44_png_array' (see 'copyright' section)\&. "
.ti -1c
.RI "file \fBwin32_SmallLogo_png\&.cpp\fP"
.br
.RI "Contains a default definition of 'SmallLogo_png_array' (see 'copyright' section)\&. "
.ti -1c
.RI "file \fBwin32_SmallLogo_png\&.hpp\fP"
.br
.RI "Contains a default declaration of 'SmallLogo_png_array' (see 'copyright' section)\&. "
.ti -1c
.RI "file \fBwin32_SplashScreen_png\&.cpp\fP"
.br
.RI "Contains a default definition of 'SplashScreen_png_array' (see 'copyright' section)\&. "
.ti -1c
.RI "file \fBwin32_SplashScreen_png\&.hpp\fP"
.br
.RI "Contains a default declaration of 'SplashScreen_png_array' (see 'copyright' section)\&. "
.ti -1c
.RI "file \fBwin32_StoreLogo_png\&.cpp\fP"
.br
.RI "Contains a default definition of 'StoreLogo_png_array' (see 'copyright' section)\&. "
.ti -1c
.RI "file \fBwin32_StoreLogo_png\&.hpp\fP"
.br
.RI "Contains a default definition of 'StoreLogo_png_array' (see 'copyright' section)\&. "
.in -1c
