.TH "include/CxxWin/modules/Win32_resource Directory Reference" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_resource Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBimg\fP"
.br
.ti -1c
.RI "directory \fBkey\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcmrc\&.hpp\fP"
.br
.ti -1c
.RI "file \fBwin32_resource\&.cpp\fP"
.br
.ti -1c
.RI "file \fBwin32_resource\&.hpp\fP"
.br
.ti -1c
.RI "file \fBwin32_resource\&.mm\fP"
.br
.in -1c
