.TH "include/CxxWin/modules/Win32_core/system Directory Reference" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_core/system Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBwin32_CompilerSupport\&.hpp\fP"
.br
.RI "Contains preprocessor definitions that attempt to detect compiler information\&. "
.ti -1c
.RI "file \fBwin32_PlatformDefs\&.hpp\fP"
.br
.RI "Contains preprocessor definitions to declare classes and structs as 'non-copyable', 'non-moveable', and to add a leak detector for debugging\&. "
.ti -1c
.RI "file \fBwin32_StandardHeader\&.hpp\fP"
.br
.RI "Contains some standard definitions, functions, and includes familiar to all supported platforms and architectures\&. "
.ti -1c
.RI "file \fBwin32_TargetPlatform\&.hpp\fP"
.br
.RI "Provides some preprocessor feature detection handlers to attempt to ascertain information about the build architecture and platform\&. "
.ti -1c
.RI "file \fBwin32_Toolchain\&.hpp\fP"
.br
.in -1c
