.TH "include/CxxWin/modules Directory Reference" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBWin32_core\fP"
.br
.ti -1c
.RI "directory \fBWin32_resource\fP"
.br
.in -1c
