.TH "include/CxxWin/modules/Win32_core/native Directory Reference" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_core/native Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBwin32_BasicNativeHeaders\&.hpp\fP"
.br
.RI "Uses compiler feature detection macros to scan for and include required system headers and libraries\&. "
.ti -1c
.RI "file \fBwin32_Unicode\&.hpp\fP"
.br
.RI "Provides preprocessor handling for switching the behaviour of some important functions such as 'TEXT()', between 'ANSI' and 'Unicode' styles\&. "
.in -1c
