.TH "include/CxxWin/modules/Win32_core/memory Directory Reference" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_core/memory Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBwin32_CComPtrBase\&.hpp\fP"
.br
.ti -1c
.RI "file \fBwin32_SmartPointer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBwin32_SmartPointer\&.hpp\fP"
.br
.RI "Contains the definition of a simple COM '\fBSmartPointer\fP' class\&. "
.in -1c
