.TH "CMakeRC::Key::Windows_TemporaryKey" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMakeRC::Key::Windows_TemporaryKey \- '  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBRCRESOURCEPTR\fP const \fBWindows_TemporaryKey_pfx_begin\fP = ::Windows_TemporaryKey_pfx_array"
.br
.RI "Pointer to the beginning of 'Windows_TemporaryKey_pfx_array'\&. "
.ti -1c
.RI "\fBRCRESOURCEPTR\fP const \fBWindows_TemporaryKey_pfx_end\fP = ::Windows_TemporaryKey_pfx_array + 2560"
.br
.RI "Pointer to the end of 'Windows_TemporaryKey_pfx_array'\&. "
.in -1c
.SH "Detailed Description"
.PP 
' 

The '\fBWindows_TemporaryKey\fP' namespace\&. Contains declarations and definitions of binary-compiled 'Windows_TemporaryKey\&.pfx' for interacting with \fBWin32\fP API\&. 
.SH "Variable Documentation"
.PP 
.SS "\fBRCRESOURCEPTR\fP const CMakeRC::Key::Windows_TemporaryKey::Windows_TemporaryKey_pfx_begin = ::Windows_TemporaryKey_pfx_array\fC [extern]\fP"

.PP
Pointer to the beginning of 'Windows_TemporaryKey_pfx_array'\&. 
.SS "\fBRCRESOURCEPTR\fP const CMakeRC::Key::Windows_TemporaryKey::Windows_TemporaryKey_pfx_end = ::Windows_TemporaryKey_pfx_array + 2560\fC [extern]\fP"

.PP
Pointer to the end of 'Windows_TemporaryKey_pfx_array'\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
