.TH "CMakeRC::Img::SmallLogo" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMakeRC::Img::SmallLogo \- The '\fBSmallLogo\fP' namespace\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBRCRESOURCEPTR\fP const \fBSmallLogo_png_begin\fP = ::SmallLogo_png_array"
.br
.RI "Pointer to the beginning of 'SmallLogo_png_array'\&. "
.ti -1c
.RI "\fBRCRESOURCEPTR\fP const \fBSmallLogo_png_end\fP = ::SmallLogo_png_array + 167"
.br
.RI "Pointer to the end of 'SmallLogo_png_array'\&. "
.in -1c
.SH "Detailed Description"
.PP 
The '\fBSmallLogo\fP' namespace\&. 

Contains declarations and definitions of binary-compiled 'SmallLogo\&.png' for interacting with \fBWin32\fP API\&. 
.SH "Variable Documentation"
.PP 
.SS "const char *const CMakeRC::Img::SmallLogo::SmallLogo_png_begin = ::SmallLogo_png_array\fC [extern]\fP"

.PP
Pointer to the beginning of 'SmallLogo_png_array'\&. Pointer to the Beginning of 'SmallLogo_png_array'\&. 
.SS "const char *const CMakeRC::Img::SmallLogo::SmallLogo_png_end = ::SmallLogo_png_array + 167\fC [extern]\fP"

.PP
Pointer to the end of 'SmallLogo_png_array'\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
