.TH "CMakeRC::Key::StoreLogo" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMakeRC::Key::StoreLogo \- '  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
' 

The '\fBStoreLogo\fP' namespace\&. Contains declarations and definitions of binary-compiled 'StoreLogo\&.png' for interacting with \fBWin32\fP API\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
