.TH "CMakeRC::Img" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMakeRC::Img \- '  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBanonymous_namespace{win32_png\&.cpp}\fP"
.br
.ti -1c
.RI "namespace \fBanonymous_namespace{win32_png\&.hpp}\fP"
.br
.ti -1c
.RI "namespace \fBApplicationIcon\fP"
.br
.RI "' "
.ti -1c
.RI "namespace \fBLogo\fP"
.br
.RI "' "
.ti -1c
.RI "namespace \fBSmallLogo\fP"
.br
.RI "The '\fBSmallLogo\fP' namespace\&. "
.ti -1c
.RI "namespace \fBSmallLogo44x44\fP"
.br
.RI "The '\fBSmallLogo44x44\fP' namespace\&. "
.ti -1c
.RI "namespace \fBSplashScreen\fP"
.br
.RI "' "
.ti -1c
.RI "namespace \fBStoreLogo\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBFSEMBEDDED\fP \fBGetFileSystem\fP ()"
.br
.RI "Get the '\fBCMakeRC::EmbeddedFileSystem\fP' '\fBCMakeRC::Detail::IndexType\fP' object\&. "
.in -1c
.SH "Detailed Description"
.PP 
' 

The '\fBImg\fP' namespace\&. Contains declarations and definitions of binary-compiled '*\&.png' files for interacting with \fBWin32\fP API\&. 
.SH "Function Documentation"
.PP 
.SS "\fBFSEMBEDDED\fP CMakeRC::Img::GetFileSystem ()"

.PP
Get the '\fBCMakeRC::EmbeddedFileSystem\fP' '\fBCMakeRC::Detail::IndexType\fP' object\&. 
.PP
\fBReturns\fP
.RS 4
'FSEMBEDDED' 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
