.TH "CMakeRC::Detail" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMakeRC::Detail \- '  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCreatedSubDirectory\fP"
.br
.ti -1c
.RI "class \fBDirectory\fP"
.br
.ti -1c
.RI "class \fBFileData\fP"
.br
.ti -1c
.RI "class \fBFileOrDirectory\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBIndexType\fP = std::map< std::string, const \fBCMakeRC::Detail::FileOrDirectory\fP * >"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::pair< std::string, std::string > \fBSplitPath\fP (const std::string &path)"
.br
.ti -1c
.RI "std::string \fBNormalizePath\fP (std::string path)"
.br
.in -1c
.SH "Detailed Description"
.PP 
' 

The '\fBFileData\fP' class ::
.PP
The '\fBCMakeRC::Detail\fP' namespace\&.
.SH "Typedef Documentation"
.PP 
.SS "using \fBCMakeRC::Detail::IndexType\fP = typedef std::map<std::string, const \fBCMakeRC::Detail::FileOrDirectory\fP*>"

.SH "Function Documentation"
.PP 
.SS "std::string CMakeRC::Detail::NormalizePath (std::string path)\fC [inline]\fP"

.PP
\fBParameters\fP
.RS 4
\fIpath\fP 
.RE
.PP
\fBReturns\fP
.RS 4
std::string 
.RE
.PP

.SS "std::pair< std::string, std::string > CMakeRC::Detail::SplitPath (const std::string & path)\fC [inline]\fP"

.PP
\fBParameters\fP
.RS 4
\fIpath\fP 
.RE
.PP
\fBReturns\fP
.RS 4
std::pair<std::string, std::string> 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
