.TH "CMakeRC::Img::Logo" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMakeRC::Img::Logo \- '  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBRCRESOURCEPTR\fP const \fBLogo_png_begin\fP = ::Logo_png_array"
.br
.RI "Pointer to the beginning of 'Logo_png_array'\&. "
.ti -1c
.RI "\fBRCRESOURCEPTR\fP const \fBLogo_png_end\fP = ::Logo_png_array + 488"
.br
.RI "Pointer to the end of 'Logo_png_array'\&. "
.in -1c
.SH "Detailed Description"
.PP 
' 

The '\fBLogo\fP' namespace\&. Contains declarations and definitions of binary-compiled 'Logo\&.png' for interacting with \fBWin32\fP API\&. 
.SH "Variable Documentation"
.PP 
.SS "\fBRCRESOURCEPTR\fP const CMakeRC::Img::Logo::Logo_png_begin = ::Logo_png_array\fC [extern]\fP"

.PP
Pointer to the beginning of 'Logo_png_array'\&. 
.SS "\fBRCRESOURCEPTR\fP const CMakeRC::Img::Logo::Logo_png_end = ::Logo_png_array + 488\fC [extern]\fP"

.PP
Pointer to the end of 'Logo_png_array'\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
