.TH "CMakeRC::File" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMakeRC::File
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmrc\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBIterator\fP = \fBRCRESOURCEPTR\fP"
.br
.ti -1c
.RI "using \fBConstIterator\fP = \fBIterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFile\fP ()=default"
.br
.RI "Default-Construct a new '\fBFile\fP' object\&. "
.ti -1c
.RI "\fBFile\fP (\fBIterator\fP beg, \fBIterator\fP end) noexcept"
.br
.RI "Construct a new '\fBFile\fP' object\&. "
.ti -1c
.RI "\fBIterator\fP \fBBegin\fP () const noexcept"
.br
.RI "Return the beginning of an array which contains a '\fBFile\fP' object\&. "
.ti -1c
.RI "\fBIterator\fP \fBCBegin\fP () const noexcept"
.br
.RI "Return the beginning of an array which contains a '\fBFile\fP' object\&. "
.ti -1c
.RI "\fBIterator\fP \fBEnd\fP () const noexcept"
.br
.RI "Return the end of an array which contains a '\fBFile\fP' object\&. "
.ti -1c
.RI "\fBIterator\fP \fBCEnd\fP () const noexcept"
.br
.RI "Return the end of an array which contains a '\fBFile\fP' object\&. "
.ti -1c
.RI "std::size_t \fBSize\fP () const"
.br
.RI "Return the size of an array which contains a '\fBFile\fP' object\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBRCRESOURCEPTR\fP \fB_begin\fP = nullptr"
.br
.RI "The first char of an array which contains a 'file' object\&. "
.ti -1c
.RI "\fBRCRESOURCEPTR\fP \fB_end\fP = nullptr"
.br
.RI "The last char of an array which contains a 'file' object\&. "
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBCMakeRC::File::ConstIterator\fP =  \fBIterator\fP"

.SS "using \fBCMakeRC::File::Iterator\fP =  \fBRCRESOURCEPTR\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "CMakeRC::File::File ()\fC [default]\fP"

.PP
Default-Construct a new '\fBFile\fP' object\&. 
.SS "CMakeRC::File::File (\fBIterator\fP beg, \fBIterator\fP end)\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Construct a new '\fBFile\fP' object\&. 
.PP
\fBParameters\fP
.RS 4
\fIbeg\fP 
.br
\fIend\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBIterator\fP CMakeRC::File::Begin () const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Return the beginning of an array which contains a '\fBFile\fP' object\&. 
.PP
\fBReturns\fP
.RS 4
Iterator 
.RE
.PP

.SS "\fBIterator\fP CMakeRC::File::CBegin () const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Return the beginning of an array which contains a '\fBFile\fP' object\&. 
.PP
\fBReturns\fP
.RS 4
Iterator 
.RE
.PP

.SS "\fBIterator\fP CMakeRC::File::CEnd () const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Return the end of an array which contains a '\fBFile\fP' object\&. 
.PP
\fBReturns\fP
.RS 4
Iterator 
.RE
.PP

.SS "\fBIterator\fP CMakeRC::File::End () const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
Return the end of an array which contains a '\fBFile\fP' object\&. 
.PP
\fBReturns\fP
.RS 4
Iterator 
.RE
.PP

.SS "std::size_t CMakeRC::File::Size () const\fC [inline]\fP"

.PP
Return the size of an array which contains a '\fBFile\fP' object\&. 
.PP
\fBReturns\fP
.RS 4
std::size_t 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "\fBRCRESOURCEPTR\fP CMakeRC::File::_begin = nullptr\fC [private]\fP"

.PP
The first char of an array which contains a 'file' object\&. 
.SS "\fBRCRESOURCEPTR\fP CMakeRC::File::_end = nullptr\fC [private]\fP"

.PP
The last char of an array which contains a 'file' object\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
