.TH "CMakeRC::Detail::Directory" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMakeRC::Detail::Directory
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmrc\&.hpp>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIterator\fP"
.br
.RI "The '\fBIterator\fP' class\&. "
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBConstIterator\fP = \fBIterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDirectory\fP ()=default"
.br
.RI "Construct a new '\fBDirectory\fP' object\&. "
.ti -1c
.RI "\fBDirectory\fP (const \fBDirectory\fP &)=delete"
.br
.RI "(inaccessible) Move-Construct a new '\fBDirectory\fP' object\&. "
.ti -1c
.RI "\fBCreatedSubDirectory\fP \fBAddSubDir\fP (std::string name) &"
.br
.ti -1c
.RI "\fBFileOrDirectory\fP * \fBAddFile\fP (std::string name, \fBRCRESOURCEPTR\fP begin, \fBRCRESOURCEPTR\fP end) &"
.br
.ti -1c
.RI "const \fBFileOrDirectory\fP * \fBGet\fP (const std::string &path) const"
.br
.ti -1c
.RI "\fBIterator\fP \fBBegin\fP () const noexcept"
.br
.ti -1c
.RI "\fBIterator\fP \fBEnd\fP () const noexcept"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "using \fBBaseIterator\fP = std::map< std::string, \fBFileOrDirectory\fP >::const_iterator"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::list< \fBFileData\fP > \fB_files\fP"
.br
.ti -1c
.RI "std::list< \fBDirectory\fP > \fB_dirs\fP"
.br
.ti -1c
.RI "std::map< std::string, \fBFileOrDirectory\fP > \fB_index\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBCMakeRC::Detail::Directory::BaseIterator\fP =  std::map<std::string, \fBFileOrDirectory\fP>::const_iterator\fC [private]\fP"

.SS "using \fBCMakeRC::Detail::Directory::ConstIterator\fP =  \fBIterator\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "CMakeRC::Detail::Directory::Directory ()\fC [default]\fP"

.PP
Construct a new '\fBDirectory\fP' object\&. 
.SS "CMakeRC::Detail::Directory::Directory (const \fBDirectory\fP &)\fC [delete]\fP"

.PP
(inaccessible) Move-Construct a new '\fBDirectory\fP' object\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBFileOrDirectory\fP * CMakeRC::Detail::Directory::AddFile (std::string name, \fBRCRESOURCEPTR\fP begin, \fBRCRESOURCEPTR\fP end) &\fC [inline]\fP"

.PP
\fBParameters\fP
.RS 4
\fIname\fP 
.br
\fIbegin\fP 
.br
\fIend\fP 
.RE
.PP
\fBReturns\fP
.RS 4
FileOrDirectory* 
.RE
.PP

.SS "\fBCreatedSubDirectory\fP CMakeRC::Detail::Directory::AddSubDir (std::string name) &\fC [inline]\fP"

.PP
\fBParameters\fP
.RS 4
\fIname\fP 
.RE
.PP
\fBReturns\fP
.RS 4
\fBCreatedSubDirectory\fP 
.RE
.PP

.SS "\fBIterator\fP CMakeRC::Detail::Directory::Begin () const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
\fBReturns\fP
.RS 4
\fBIterator\fP 
.RE
.PP

.SS "\fBIterator\fP CMakeRC::Detail::Directory::End () const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
\fBReturns\fP
.RS 4
\fBIterator\fP 
.RE
.PP

.SS "const \fBFileOrDirectory\fP * CMakeRC::Detail::Directory::Get (const std::string & path) const\fC [inline]\fP"

.PP
\fBParameters\fP
.RS 4
\fIpath\fP 
.RE
.PP
\fBReturns\fP
.RS 4
const FileOrDirectory* 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "std::list<\fBDirectory\fP> CMakeRC::Detail::Directory::_dirs\fC [private]\fP"

.SS "std::list<\fBFileData\fP> CMakeRC::Detail::Directory::_files\fC [private]\fP"

.SS "std::map<std::string, \fBFileOrDirectory\fP> CMakeRC::Detail::Directory::_index\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
