.TH "CMakeRC::Key" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMakeRC::Key \- '  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBanonymous_namespace{win32_pfx\&.cpp}\fP"
.br
.ti -1c
.RI "namespace \fBanonymous_namespace{win32_pfx\&.hpp}\fP"
.br
.ti -1c
.RI "namespace \fBStoreLogo\fP"
.br
.RI "' "
.ti -1c
.RI "namespace \fBWindows_TemporaryKey\fP"
.br
.RI "' "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBFSEMBEDDED\fP \fBGetFileSystem\fP ()"
.br
.RI "Get the '\fBCMakeRC::EmbeddedFileSystem\fP' '\fBCMakeRC::Detail::IndexType\fP' object\&. "
.in -1c
.SH "Detailed Description"
.PP 
' 

The '\fBCMakeRC::Key\fP' namespace\&. This namespace contains definitions and declarations of keys that have been compiled into binary bits\&. It also contains functions to provide a handle to those keys\&. 
.SH "Function Documentation"
.PP 
.SS "\fBFSEMBEDDED\fP CMakeRC::Key::GetFileSystem ()"

.PP
Get the '\fBCMakeRC::EmbeddedFileSystem\fP' '\fBCMakeRC::Detail::IndexType\fP' object\&. 
.PP
\fBReturns\fP
.RS 4
'FSEMBEDDED' 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
