.TH "CMakeRC::Detail::FileOrDirectory" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMakeRC::Detail::FileOrDirectory
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmrc\&.hpp>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "union \fB_data_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileOrDirectory\fP (\fBFileData\fP &f)"
.br
.RI "Construct a new '\fBFileOrDirectory\fP' object\&. "
.ti -1c
.RI "\fBFileOrDirectory\fP (\fBDirectory\fP &d)"
.br
.RI "Construct a new '\fBFileOrDirectory\fP' object\&. "
.ti -1c
.RI "bool \fBIsFile\fP () const noexcept"
.br
.ti -1c
.RI "bool \fBIsDirectory\fP () const noexcept"
.br
.ti -1c
.RI "const \fBDirectory\fP & \fBAsDirectory\fP () const noexcept"
.br
.ti -1c
.RI "const \fBFileData\fP & \fBAsFile\fP () const noexcept"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "union \fBCMakeRC::Detail::FileOrDirectory::_data_t\fP \fB_data\fP"
.br
.ti -1c
.RI "bool \fB_is_file\fP = true"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CMakeRC::Detail::FileOrDirectory::FileOrDirectory (\fBFileData\fP & f)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Construct a new '\fBFileOrDirectory\fP' object\&. 
.PP
\fBParameters\fP
.RS 4
\fIf\fP 
.RE
.PP

.SS "CMakeRC::Detail::FileOrDirectory::FileOrDirectory (\fBDirectory\fP & d)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Construct a new '\fBFileOrDirectory\fP' object\&. 
.PP
\fBParameters\fP
.RS 4
\fId\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "const \fBDirectory\fP & CMakeRC::Detail::FileOrDirectory::AsDirectory () const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
\fBReturns\fP
.RS 4
const \fBDirectory\fP& 
.RE
.PP

.SS "const \fBFileData\fP & CMakeRC::Detail::FileOrDirectory::AsFile () const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
\fBReturns\fP
.RS 4
const \fBFileData\fP& 
.RE
.PP

.SS "bool CMakeRC::Detail::FileOrDirectory::IsDirectory () const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
\fBReturns\fP
.RS 4
true 
.PP
false 
.RE
.PP

.SS "bool CMakeRC::Detail::FileOrDirectory::IsFile () const\fC [inline]\fP, \fC [noexcept]\fP"

.PP
\fBReturns\fP
.RS 4
true 
.PP
false 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "union \fBCMakeRC::Detail::FileOrDirectory::_data_t\fP CMakeRC::Detail::FileOrDirectory::_data\fC [private]\fP"

.SS "bool CMakeRC::Detail::FileOrDirectory::_is_file = true\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
