.TH "CMakeRC::Img::anonymous_namespace{win32_png.cpp}" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMakeRC::Img::anonymous_namespace{win32_png.cpp}
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "const \fBIDXRES\fP & \fBGetRootIndex\fP ()"
.br
.RI "Get the '\fBCMakeRC::Detail::IndexType\fP' object\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "const \fBIDXRES\fP & CMakeRC::Img::anonymous_namespace{win32_png\&.cpp}::GetRootIndex ()"

.PP
Get the '\fBCMakeRC::Detail::IndexType\fP' object\&. 
.PP
\fBReturns\fP
.RS 4
const '\fBCMakeRC::Detail::IndexType\fP' & 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
