.TH "CMakeRC::Detail::FileData" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMakeRC::Detail::FileData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmrc\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileData\fP (\fBRCRESOURCEPTR\fP b, \fBRCRESOURCEPTR\fP e)"
.br
.RI "Construct a new '\fBFileData\fP' object\&. "
.ti -1c
.RI "\fBFileData\fP (const \fBFileData\fP &)=delete"
.br
.RI "(inaccessible) Move-Construct a new '\fBFileData\fP' object "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRCRESOURCEPTR\fP \fBbegin_ptr\fP"
.br
.ti -1c
.RI "\fBRCRESOURCEPTR\fP \fBend_ptr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CMakeRC::Detail::FileData::FileData (\fBRCRESOURCEPTR\fP b, \fBRCRESOURCEPTR\fP e)\fC [inline]\fP"

.PP
Construct a new '\fBFileData\fP' object\&. 
.PP
\fBParameters\fP
.RS 4
\fIb\fP 
.br
\fIe\fP 
.RE
.PP

.SS "CMakeRC::Detail::FileData::FileData (const \fBFileData\fP &)\fC [delete]\fP"

.PP
(inaccessible) Move-Construct a new '\fBFileData\fP' object 
.SH "Member Data Documentation"
.PP 
.SS "\fBRCRESOURCEPTR\fP CMakeRC::Detail::FileData::begin_ptr"

.SS "\fBRCRESOURCEPTR\fP CMakeRC::Detail::FileData::end_ptr"


.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
