.TH "CMakeRC" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMakeRC \- '  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDetail\fP"
.br
.RI "' "
.ti -1c
.RI "namespace \fBImg\fP"
.br
.RI "' "
.ti -1c
.RI "namespace \fBKey\fP"
.br
.RI "' "
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDirectoryEntry\fP"
.br
.ti -1c
.RI "class \fBEmbeddedFileSystem\fP"
.br
.ti -1c
.RI "class \fBFile\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBDirectoryIterator\fP = \fBDetail::Directory::Iterator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
' 

The '\fBEmbeddedFileSystem\fP' class\&.
.PP
The 'CreatedSubDirectory' struct\&.
.PP
The 'FileOrDirectory' class\&.
.PP
The 'FileData' class\&.
.PP
The 'Directory' class\&.
.PP
The '\fBDirectoryEntry\fP' class\&.
.PP
The '\fBFile\fP' class\&.
.PP
Dummy struct\&.
.PP
The '\fBCMakeRC\fP' namespace\&.
.SH "Typedef Documentation"
.PP 
.SS "using \fBCMakeRC::DirectoryIterator\fP = typedef \fBDetail::Directory::Iterator\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
