.TH "CMakeRC::Detail::FileOrDirectory::_data_t" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMakeRC::Detail::FileOrDirectory::_data_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "class \fBFileData\fP * \fBFileData\fP"
.br
.ti -1c
.RI "class \fBDirectory\fP * \fBDirectory\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "class \fBDirectory\fP* CMakeRC::Detail::FileOrDirectory::_data_t::Directory"

.SS "class \fBFileData\fP* CMakeRC::Detail::FileOrDirectory::_data_t::FileData"


.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
