.TH "CMakeRC::Key::anonymous_namespace{win32_pfx.cpp}" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMakeRC::Key::anonymous_namespace{win32_pfx.cpp}
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "const \fBIDXRES\fP & \fBGetRootIndex\fP ()"
.br
.RI "Get the '\fBCMakeRC::Detail::IndexType\fP' object\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "const \fBIDXRES\fP & CMakeRC::Key::anonymous_namespace{win32_pfx\&.cpp}::GetRootIndex ()"

.PP
Get the '\fBCMakeRC::Detail::IndexType\fP' object\&. 
.PP
\fBReturns\fP
.RS 4
const 'IDXRES' & 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
