.TH "include/CxxWin/modules/Win32_resource/cmrc.hpp" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_resource/cmrc.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cassert>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <list>\fP
.br
\fC#include <map>\fP
.br
\fC#include <mutex>\fP
.br
\fC#include <string>\fP
.br
\fC#include <system_error>\fP
.br
\fC#include <type_traits>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCMakeRC::File\fP"
.br
.ti -1c
.RI "class \fBCMakeRC::Detail::FileOrDirectory\fP"
.br
.ti -1c
.RI "union \fBCMakeRC::Detail::FileOrDirectory::_data_t\fP"
.br
.ti -1c
.RI "class \fBCMakeRC::Detail::FileData\fP"
.br
.ti -1c
.RI "struct \fBCMakeRC::Detail::CreatedSubDirectory\fP"
.br
.ti -1c
.RI "class \fBCMakeRC::Detail::Directory\fP"
.br
.ti -1c
.RI "class \fBCMakeRC::Detail::Directory::Iterator\fP"
.br
.RI "The '\fBIterator\fP' class\&. "
.ti -1c
.RI "class \fBCMakeRC::DirectoryEntry\fP"
.br
.ti -1c
.RI "class \fBCMakeRC::EmbeddedFileSystem\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCMakeRC\fP"
.br
.RI "' "
.ti -1c
.RI "namespace \fBCMakeRC::Detail\fP"
.br
.RI "' "
.ti -1c
.RI "namespace \fBDetail\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCMRC_NO_EXCEPTIONS\fP   1"
.br
.RI "If defined: Disable C++ exceptions in \fBCMakeRC\fP structures\&. "
.ti -1c
.RI "#define \fBCMRC_DECLARE\fP(LibId)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBCMakeRC::Detail::IndexType\fP = std::map< std::string, const \fBCMakeRC::Detail::FileOrDirectory\fP * >"
.br
.ti -1c
.RI "using \fBCMakeRC::DirectoryIterator\fP = \fBDetail::Directory::Iterator\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::pair< std::string, std::string > \fBCMakeRC::Detail::SplitPath\fP (const std::string &path)"
.br
.ti -1c
.RI "std::string \fBCMakeRC::Detail::NormalizePath\fP (std::string path)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
vector-of-bool vectorofbool@gmail.com 
.RE
.PP
\fBVersion\fP
.RS 4
2\&.0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2018-09-08
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2017
.RE
.PP
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\&.
.PP
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#define CMRC_DECLARE(LibId)"
\fBValue:\fP.PP
.nf
namespace CMakeRC \\
{ \\
namespace Detail \\
{ \\
struct Dummy; \\
static_assert(std::is_same<Dummy, ::CMakeRC::Detail::Dummy>::value, "CMRC_DECLARE() must only appear at the global namespace"); \\
} \\
} \\
namespace CMakeRC \\
{ \\
namespace LibId \\
{ \\
CMakeRC::EmbeddedFileSystem GetFileSystem(); \\
} \\
} static_assert(true, "")
.fi

.SS "#define CMRC_NO_EXCEPTIONS   1"

.PP
If defined: Disable C++ exceptions in \fBCMakeRC\fP structures\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
