.TH "Logo" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Logo \- '  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
' 

The '\fBLogo\fP' namespace\&. Contains declarations and definitions of binary-compiled 'Logo\&.png' for interacting with \fBWin32\fP API\&.
.PP
\fBSee also\fP
.RS 4
'Logo\&.png' 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
