.TH "include/CxxWin/MainComponent.hpp" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/MainComponent.hpp \- Contains the declarations of '\fBMainComponent\fP'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'modules/Win32_core/win32_core\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainComponent\fP"
.br
.RI "The '\fBMainComponent\fP' class\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_MAIN_COMPONENT_HPP_\fP"
.br
.RI "Contains the declarations of '\fBMainComponent\fP'\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains the declarations of '\fBMainComponent\fP'\&. 


.PP
\fBAuthor\fP
.RS 4
StoneyDSP (nathanjhood@googlemail.com) 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2023-08-28
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define _MAIN_COMPONENT_HPP_"

.PP
Contains the declarations of '\fBMainComponent\fP'\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
