.TH "SmartPointerHelper< ComClasses >" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SmartPointerHelper< ComClasses > \- The '\fBSmartPointerHelper\fP' class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <win32_SmartPointer\&.hpp>\fP
.PP
Inherits \fBSmartPointerHelperBase< ComClasses\&.\&.\&. >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSmartPointerHelper\fP (unsigned int initRef)"
.br
.RI "Construct a new '\fBSmartPointerHelper\fP' object\&. "
.ti -1c
.RI "HRESULT STDMETHODCALLTYPE \fBQueryInterface\fP (REFIID refId, void **result)"
.br
.RI "Query the interface to the underlying COM object\&. "
.in -1c

Public Member Functions inherited from \fBSmartPointerHelperBase< ComClasses\&.\&.\&. >\fP
.in +1c
.ti -1c
.RI "\fBSmartPointerHelperBase\fP (unsigned int initRef)"
.br
.RI "Construct a new '\fBSmartPointerHelperBase\fP' object\&. "
.ti -1c
.RI "virtual \fB~SmartPointerHelperBase\fP ()=default"
.br
.RI "Destroy the '\fBSmartPointerHelperBase\fP' object\&. "
.ti -1c
.RI "ULONG STDMETHODCALLTYPE \fBAddRef\fP ()"
.br
.RI "Add a new reference to the pointer, increasing the counter by one\&. "
.ti -1c
.RI "ULONG STDMETHODCALLTYPE \fBRelease\fP ()"
.br
.RI "Release a reference to the pointer, decreasing the counter by one\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBSmartPointerHelperBase< ComClasses\&.\&.\&. >\fP
.in +1c
.ti -1c
.RI "HRESULT STDMETHODCALLTYPE \fBcastToType\fP (void **result)"
.br
.RI "Add a new reference to the pointer (increasing the counter by one), and attempt to cast to type 'T'\&. "
.ti -1c
.RI "HRESULT STDMETHODCALLTYPE \fBQueryInterface\fP (REFIID riid, void **ppvObject)"
.br
.RI "Query a COM object for a pointer to one its interfaces, identifying the interface by a reference to its interface identifier (IID)\&. "
.in -1c

Protected Attributes inherited from \fBSmartPointerHelperBase< ComClasses\&.\&.\&. >\fP
.in +1c
.ti -1c
.RI "ULONG \fBrefCount\fP"
.br
.RI "The underlying reference counter to the pointer\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class\&.\&.\&. ComClasses>
.br
class SmartPointerHelper< ComClasses >"The '\fBSmartPointerHelper\fP' class\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIComClasses\fP 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class\&.\&.\&. ComClasses> \fBSmartPointerHelper\fP< ComClasses >\fB::SmartPointerHelper\fP (unsigned int initRef)\fC [explicit]\fP"

.PP
Construct a new '\fBSmartPointerHelper\fP' object\&. 
.PP
\fBParameters\fP
.RS 4
\fIinitRef\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<class\&.\&.\&. ComClasses> HRESULT \fBSmartPointerHelper\fP< ComClasses >::QueryInterface (REFIID refId, void ** result)"

.PP
Query the interface to the underlying COM object\&. 
.PP
\fBParameters\fP
.RS 4
\fIrefId\fP 
.br
\fIresult\fP 
.RE
.PP
\fBReturns\fP
.RS 4
HRESULT 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
