.TH "include/CxxWin/modules/Win32_core/win32_core.mm" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_core/win32_core.mm
.SH SYNOPSIS
.br
.PP
\fC#include 'win32_core\&.cpp'\fP
.br

.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
StoneyDSP (nathanjhood@googlemail.com) 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2023-08-24
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
