.TH "include/CxxWin/modules/Win32_core/memory/win32_SmartPointer.hpp" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_core/memory/win32_SmartPointer.hpp \- Contains the definition of a simple COM '\fBSmartPointer\fP' class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSmartPointer< ComClass >\fP"
.br
.RI "The '\fBSmartPointer\fP' class\&. "
.ti -1c
.RI "class \fBSmartPointerHelperBase< First, ComClasses >\fP"
.br
.RI "The '\fBSmartPointerHelperBase\fP' class\&. "
.ti -1c
.RI "class \fBSmartPointerHelper< ComClasses >\fP"
.br
.RI "The '\fBSmartPointerHelper\fP' class\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_WIN32_SMARTPOINTER_HPP_\fP"
.br
.RI "Contains the definition of a simple COM '\fBSmartPointer\fP' class\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class ComClass > void \fBSafeRelease\fP (ComClass **ptr)"
.br
.RI "If the pointer is valid, call the underlying 'Release' method on it, and set it to 'nullptr'\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains the definition of a simple COM '\fBSmartPointer\fP' class\&. 


.PP
\fBAuthor\fP
.RS 4
StoneyDSP (nathanjhood@googlemail.com)
.RE
.PP
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2023-08-25
.RE
.PP
\fBCopyright\fP
.RS 4
This file is part of the JUCE library\&. Copyright (c) 2022 - Raw Material Software Limited
.RE
.PP
JUCE is an open source library subject to commercial or open-source licensing\&.
.PP
The code included in this file is provided under the terms of the ISC license http://www.isc.org/downloads/software-support-policy/isc-license\&. Permission To use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted provided that the above copyright notice and this permission notice appear in all copies\&.
.PP
JUCE IS PROVIDED 'AS IS' WITHOUT ANY WARRANTY, AND ALL WARRANTIES, WHETHER EXPRESSED OR IMPLIED, INCLUDING MERCHANTABILITY AND FITNESS FOR PURPOSE, ARE DISCLAIMED\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#define _WIN32_SMARTPOINTER_HPP_"

.PP
Contains the definition of a simple COM '\fBSmartPointer\fP' class\&. 
.SH "Function Documentation"
.PP 
.SS "template<class ComClass > void SafeRelease (ComClass ** ptr)"

.PP
If the pointer is valid, call the underlying 'Release' method on it, and set it to 'nullptr'\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIComClass\fP 
.RE
.PP
\fBParameters\fP
.RS 4
\fIptr\fP Accepts a pointer to a COM class or struct object\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
