.TH "include/CxxWin/modules/Win32_core/memory/win32_CComPtrBase.hpp" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_core/memory/win32_CComPtrBase.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCComPtrBase< T >\fP"
.br
.RI "The '\fBCComPtrBase\fP' class\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__WIN32_CORE_MEMORY_CCOMPTRBASE_HPP__\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
StoneyDSP (nathanjhood@googlemail.com) 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2023-09-04
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023
.RE
.PP
\fBhttps://learn\&.microsoft\&.com/en-us/cpp/atl/reference/ccomptrbase-class?view=msvc-170\fP
.SH "Macro Definition Documentation"
.PP 
.SS "#define __WIN32_CORE_MEMORY_CCOMPTRBASE_HPP__"

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
