.TH "include/CxxWin/modules/Win32_core/native/win32_BasicNativeHeaders.hpp" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_core/native/win32_BasicNativeHeaders.hpp \- Uses compiler feature detection macros to scan for and include required system headers and libraries\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_WIN32_BASICNATIVEHEADERS_HPP_\fP"
.br
.RI "Uses compiler feature detection macros to scan for and include required system headers and libraries\&. "
.in -1c
.SH "Detailed Description"
.PP 
Uses compiler feature detection macros to scan for and include required system headers and libraries\&. 


.PP
\fBAuthor\fP
.RS 4
StoneyDSP (nathanjhood@googlemail.com)
.RE
.PP
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2023-08-30
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define _WIN32_BASICNATIVEHEADERS_HPP_"

.PP
Uses compiler feature detection macros to scan for and include required system headers and libraries\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
