.TH "include/CxxWin/modules/Win32_core/system/win32_CompilerSupport.hpp" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_core/system/win32_CompilerSupport.hpp \- Contains preprocessor definitions that attempt to detect compiler information\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_WIN32_COMPILERSUPPORT_HPP_\fP"
.br
.RI "Contains preprocessor definitions that attempt to detect compiler information\&. "
.ti -1c
.RI "#define \fB__CXX_COMPILER_NAME\fP   __C_COMPILER_NAME"
.br
.RI "Compiler support\&. "
.ti -1c
.RI "#define \fB__CXX_COMPILER_VERSION_MAJOR\fP   __C_COMPILER_VERSION_MAJOR"
.br
.ti -1c
.RI "#define \fB__CXX_COMPILER_VERSION_MINOR\fP   __C_COMPILER_VERSION_MINOR"
.br
.ti -1c
.RI "#define \fB__CXX_COMPILER_VERSION_PATCH\fP   __C_COMPILER_VERSION_PATCH"
.br
.ti -1c
.RI "#define \fB__CXX_COMPILER_VERSION\fP   __C_COMPILER_VERSION"
.br
.ti -1c
.RI "#define \fB__ICC_VERSION\fP   0"
.br
.ti -1c
.RI "#define \fB__MSC_VERSION\fP   0"
.br
.ti -1c
.RI "#define \fB__MSC_WARNING\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fB__BEGIN_DECLS\fP"
.br
.RI "Guard C code in headers, while including them from C++\&. "
.ti -1c
.RI "#define \fB__END_DECLS\fP"
.br
.ti -1c
.RI "#define \fB__HAS_FEATURE\fP(x)   FALSE"
.br
.ti -1c
.RI "#define \fB__HAS_INCLUDE\fP(x)   FALSE"
.br
.ti -1c
.RI "#define \fB__HAS_ATTRIBUTE\fP(x)   FALSE"
.br
.ti -1c
.RI "#define \fB__HAS_C_ATTRIBUTE\fP(x)   FALSE"
.br
.ti -1c
.RI "#define \fB__HAS_CPP_ATTRIBUTE\fP(x)   FALSE"
.br
.ti -1c
.RI "#define \fB__HAS_BUILTIN\fP(x)   FALSE"
.br
.ti -1c
.RI "#define \fB__HAS_EXTENSION\fP(x)   FALSE"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains preprocessor definitions that attempt to detect compiler information\&. 


.PP
\fBAuthor\fP
.RS 4
StoneyDSP (nathanjhood@googlemail.com)
.RE
.PP
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2023-08-30
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define __BEGIN_DECLS"

.PP
Guard C code in headers, while including them from C++\&. 
.SS "#define __CXX_COMPILER_NAME   __C_COMPILER_NAME"

.PP
Compiler support\&. 
.SS "#define __CXX_COMPILER_VERSION   __C_COMPILER_VERSION"

.SS "#define __CXX_COMPILER_VERSION_MAJOR   __C_COMPILER_VERSION_MAJOR"

.SS "#define __CXX_COMPILER_VERSION_MINOR   __C_COMPILER_VERSION_MINOR"

.SS "#define __CXX_COMPILER_VERSION_PATCH   __C_COMPILER_VERSION_PATCH"

.SS "#define __END_DECLS"

.SS "#define __HAS_ATTRIBUTE(x)   FALSE"

.SS "#define __HAS_BUILTIN(x)   FALSE"

.SS "#define __HAS_C_ATTRIBUTE(x)   FALSE"

.SS "#define __HAS_CPP_ATTRIBUTE(x)   FALSE"

.SS "#define __HAS_EXTENSION(x)   FALSE"

.SS "#define __HAS_FEATURE(x)   FALSE"

.SS "#define __HAS_INCLUDE(x)   FALSE"

.SS "#define __ICC_VERSION   0"

.SS "#define __MSC_VERSION   0"

.SS "#define __MSC_WARNING( \&.\&.\&.)"

.SS "#define _WIN32_COMPILERSUPPORT_HPP_"

.PP
Contains preprocessor definitions that attempt to detect compiler information\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
