.TH "include/CxxWin/modules/Win32_resource/img/win32_ApplicationIcon_png.cpp" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_resource/img/win32_ApplicationIcon_png.cpp \- Contains a default definition of 'ApplicationIcon_png_array' (see 'copyright' section)\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'win32_ApplicationIcon_png\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBanonymous_namespace{win32_ApplicationIcon_png\&.cpp}\fP"
.br
.ti -1c
.RI "namespace \fBCMakeRC\fP"
.br
.RI "' "
.ti -1c
.RI "namespace \fBCMakeRC::Img\fP"
.br
.RI "' "
.ti -1c
.RI "namespace \fBCMakeRC::Img::ApplicationIcon\fP"
.br
.RI "' "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBRCRESOURCE\fP \fBanonymous_namespace{win32_ApplicationIcon_png\&.cpp}::ApplicationIcon_png_array\fP [2336]"
.br
.RI "An array of bytes representing 'ApplicationIcon\&.png'\&. "
.ti -1c
.RI "\fBRCRESOURCEPTR\fP const \fBCMakeRC::Img::ApplicationIcon::ApplicationIcon_png_begin\fP = ::ApplicationIcon_png_array"
.br
.RI "Pointer to the beginning of 'ApplicationIcon_png_array'\&. "
.ti -1c
.RI "\fBRCRESOURCEPTR\fP const \fBCMakeRC::Img::ApplicationIcon::ApplicationIcon_png_end\fP = ::ApplicationIcon_png_array + 2335"
.br
.RI "Pointer to the end of 'ApplicationIcon_png_array'\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains a default definition of 'ApplicationIcon_png_array' (see 'copyright' section)\&. 


.PP
\fBAuthor\fP
.RS 4
StoneyDSP (nathanjhood@googlemail.com)
.RE
.PP
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2023-08-24
.RE
.PP
\fBCopyright\fP
.RS 4
This file was generated by using Vector-of-Bool's excellent '\fBCMakeRC\fP' resource compiler script from CMake's template resources for Windows\&. The results have been given minimal tweaks - mostly just text formatting - to provide a similar interface to the rest of the project's codebase\&. Please see '\fBcmrc\&.hpp\fP' and Kitware\&.org for respective license information\&.
.RE
.PP
\fBSee also\fP
.RS 4
'ApplicationIcon\&.png' 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
