.TH "include/CxxWin/modules/Win32_core/native/win32_Unicode.hpp" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_core/native/win32_Unicode.hpp \- Provides preprocessor handling for switching the behaviour of some important functions such as 'TEXT()', between 'ANSI' and 'Unicode' styles\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWin32::Core::Native::UnicodeHandler\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBWin32\fP"
.br
.ti -1c
.RI "namespace \fBWin32::Core\fP"
.br
.ti -1c
.RI "namespace \fBWin32::Core::Native\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_WIN32_UNOCIDE_HPP_\fP"
.br
.RI "Provides preprocessor handling for switching the behaviour of some important functions such as 'TEXT()', between 'ANSI' and 'Unicode' styles\&. "
.ti -1c
.RI "#define \fB_NEED_UNICODE\fP   2"
.br
.ti -1c
.RI "#define \fB__NAME_AW\fP(func)   func##A"
.br
.ti -1c
.RI "#define \fB__NAME_AW_EXT\fP(func,  ext)   func##A##ext"
.br
.ti -1c
.RI "#define \fB__NAME_UAW\fP(func)   func##_A"
.br
.ti -1c
.RI "#define \fB__NAME_UAW_EXT\fP(func,  ext)   func##_A_##ext"
.br
.ti -1c
.RI "#define \fB__STRING_AW\fP(str)   str	/* same as TEXT() from winnt\&.h */"
.br
.ti -1c
.RI "#define \fB__PROCNAMEEXT_AW\fP   'A'"
.br
.ti -1c
.RI "#define \fB__TYPEDEF_AW\fP(type)       typedef \fB__NAME_AW\fP(type) type;"
.br
.ti -1c
.RI "#define \fB__TYPEDEF_UAW\fP(type)       typedef \fB__NAME_UAW\fP(type) type;"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides preprocessor handling for switching the behaviour of some important functions such as 'TEXT()', between 'ANSI' and 'Unicode' styles\&. 


.PP
\fBAuthor\fP
.RS 4
StoneyDSP (nathanjhood@googlemail.com)
.RE
.PP
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2023-08-31
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define __NAME_AW(func)   func##A"

.SS "#define __NAME_AW_EXT(func, ext)   func##A##ext"

.SS "#define __NAME_UAW(func)   func##_A"

.SS "#define __NAME_UAW_EXT(func, ext)   func##_A_##ext"

.SS "#define __PROCNAMEEXT_AW   'A'"

.SS "#define __STRING_AW(str)   str	/* same as TEXT() from winnt\&.h */"

.SS "#define __TYPEDEF_AW(type)       typedef \fB__NAME_AW\fP(type) type;"

.SS "#define __TYPEDEF_UAW(type)       typedef \fB__NAME_UAW\fP(type) type;"

.SS "#define _NEED_UNICODE   2"

.SS "#define _WIN32_UNOCIDE_HPP_"

.PP
Provides preprocessor handling for switching the behaviour of some important functions such as 'TEXT()', between 'ANSI' and 'Unicode' styles\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
