.TH "include/CxxWin/modules/Win32_resource/img/win32_png.cpp" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_resource/img/win32_png.cpp \- Contains pointers to named resources with external linkage, so that their respective contents can be defined elsewhere\&. Also contains definitions of functions that provide access to these specifically-named resources, which necessitates external linkage\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'win32_png\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCMakeRC\fP"
.br
.RI "' "
.ti -1c
.RI "namespace \fBCMakeRC::Img\fP"
.br
.RI "' "
.ti -1c
.RI "namespace \fBCMakeRC::Img::ApplicationIcon\fP"
.br
.RI "' "
.ti -1c
.RI "namespace \fBCMakeRC::Img::Logo\fP"
.br
.RI "' "
.ti -1c
.RI "namespace \fBCMakeRC::Img::SmallLogo\fP"
.br
.RI "The '\fBSmallLogo\fP' namespace\&. "
.ti -1c
.RI "namespace \fBCMakeRC::Img::SmallLogo44x44\fP"
.br
.RI "The '\fBSmallLogo44x44\fP' namespace\&. "
.ti -1c
.RI "namespace \fBCMakeRC::Img::SplashScreen\fP"
.br
.RI "' "
.ti -1c
.RI "namespace \fBCMakeRC::Img::StoreLogo\fP"
.br
.ti -1c
.RI "namespace \fBCMakeRC::Img::anonymous_namespace{win32_png\&.cpp}\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const \fBIDXRES\fP & \fBCMakeRC::Img::anonymous_namespace{win32_png\&.cpp}::GetRootIndex\fP ()"
.br
.RI "Get the '\fBCMakeRC::Detail::IndexType\fP' object\&. "
.ti -1c
.RI "\fBFSEMBEDDED\fP \fBCMakeRC::Img::GetFileSystem\fP ()"
.br
.RI "Get the '\fBCMakeRC::EmbeddedFileSystem\fP' '\fBCMakeRC::Detail::IndexType\fP' object\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBRCRESOURCEPTR\fP const \fBCMakeRC::Img::SmallLogo::SmallLogo_png_begin\fP = ::SmallLogo_png_array"
.br
.RI "Pointer to the beginning of 'SmallLogo_png_array'\&. "
.ti -1c
.RI "\fBRCRESOURCEPTR\fP const \fBCMakeRC::Img::SmallLogo::SmallLogo_png_end\fP = ::SmallLogo_png_array + 167"
.br
.RI "Pointer to the end of 'SmallLogo_png_array'\&. "
.ti -1c
.RI "\fBRCRESOURCEPTR\fP const \fBCMakeRC::Img::SmallLogo44x44::SmallLogo44x44_png_begin\fP = ::SmallLogo44x44_png_array"
.br
.RI "Pointer to the beginning of 'SmallLogo44x44_png_array'\&. "
.ti -1c
.RI "\fBRCRESOURCEPTR\fP const \fBCMakeRC::Img::SmallLogo44x44::SmallLogo44x44_png_end\fP = ::SmallLogo44x44_png_array + 265"
.br
.RI "Pointer to the end of 'SmallLogo44x44_png_array'\&. "
.ti -1c
.RI "\fBRCRESOURCEPTR\fP const \fBCMakeRC::Img::SplashScreen::SplashScreen_png_begin\fP = ::SplashScreen_png_array"
.br
.RI "Pointer to the beginning of 'SplashScreen_png_array'\&. "
.ti -1c
.RI "\fBRCRESOURCEPTR\fP const \fBCMakeRC::Img::SplashScreen::SplashScreen_png_end\fP = ::SplashScreen_png_array + 909"
.br
.RI "Pointer to the end of 'SplashScreen_png_array'\&. "
.ti -1c
.RI "\fBRCRESOURCEPTR\fP const \fBCMakeRC::Img::StoreLogo::StoreLogo_png_begin\fP = ::StoreLogo_png_array"
.br
.RI "Pointer to the beginning of 'StoreLogo_png_array'\&. "
.ti -1c
.RI "\fBRCRESOURCEPTR\fP const \fBCMakeRC::Img::StoreLogo::StoreLogo_png_end\fP = ::StoreLogo_png_array + 227"
.br
.RI "Pointer to the end of 'StoreLogo_png_array'\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains pointers to named resources with external linkage, so that their respective contents can be defined elsewhere\&. Also contains definitions of functions that provide access to these specifically-named resources, which necessitates external linkage\&. 


.PP
\fBAuthor\fP
.RS 4
StoneyDSP (nathanjhood@googlemail.com)
.RE
.PP
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2023-08-24
.RE
.PP
\fBCopyright\fP
.RS 4
This file was generated by using Vector-of-Bool's excellent '\fBCMakeRC\fP' resource compiler script from CMake's template resources for Windows\&. The results have been given minimal tweaks - mostly just text formatting - to provide a similar interface to the rest of the project's codebase\&. Please see '\fBcmrc\&.hpp\fP' and Kitware\&.org for respective license information\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
