.TH "include/CxxWin/modules/Win32_resource/win32_resource.cpp" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_resource/win32_resource.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'win32_resource\&.hpp'\fP
.br
\fC#include 'img/win32_png\&.cpp'\fP
.br
\fC#include 'img/win32_ApplicationIcon_png\&.cpp'\fP
.br
\fC#include 'img/win32_Logo_png\&.cpp'\fP
.br
\fC#include 'img/win32_SmallLogo_png\&.cpp'\fP
.br
\fC#include 'img/win32_SmallLogo44x44_png\&.cpp'\fP
.br
\fC#include 'img/win32_SplashScreen_png\&.cpp'\fP
.br
\fC#include 'img/win32_StoreLogo_png\&.cpp'\fP
.br
\fC#include 'key/win32_pfx\&.cpp'\fP
.br
\fC#include 'key/win32_Windows_TemporaryKey_pfx\&.cpp'\fP
.br

.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
StoneyDSP (nathanjhood@googlemail.com) 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2023-09-01
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
