.TH "include/CxxWin/modules/Win32_core/window/win32_MainWindow.cpp" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_core/window/win32_MainWindow.cpp \- Contains a definition of the '\fBMainWindow\fP' class which inherits from the '\fBBaseWindow\fP' class\&. Inherit this '\fBMainWindow\fP' class for a basic window functionality\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Contains a definition of the '\fBMainWindow\fP' class which inherits from the '\fBBaseWindow\fP' class\&. Inherit this '\fBMainWindow\fP' class for a basic window functionality\&. 


.PP
\fBAuthor\fP
.RS 4
StoneyDSP (nathanjhood@googlemail.com)
.RE
.PP
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2023-08-23
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
