.TH "include/CxxWin/modules/Win32_resource/key/win32_pfx.cpp" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_resource/key/win32_pfx.cpp \- Contains pointers to named resources with external linkage, so that their respective contents can be defined elsewhere\&. Also contains definitions of functions that provide access to these specifically-named resources, which necessitates external linkage\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'win32_pfx\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCMakeRC\fP"
.br
.RI "' "
.ti -1c
.RI "namespace \fBCMakeRC::Key\fP"
.br
.RI "' "
.ti -1c
.RI "namespace \fBCMakeRC::Key::anonymous_namespace{win32_pfx\&.cpp}\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const \fBIDXRES\fP & \fBCMakeRC::Key::anonymous_namespace{win32_pfx\&.cpp}::GetRootIndex\fP ()"
.br
.RI "Get the '\fBCMakeRC::Detail::IndexType\fP' object\&. "
.ti -1c
.RI "\fBFSEMBEDDED\fP \fBCMakeRC::Key::GetFileSystem\fP ()"
.br
.RI "Get the '\fBCMakeRC::EmbeddedFileSystem\fP' '\fBCMakeRC::Detail::IndexType\fP' object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains pointers to named resources with external linkage, so that their respective contents can be defined elsewhere\&. Also contains definitions of functions that provide access to these specifically-named resources, which necessitates external linkage\&. 


.PP
\fBAuthor\fP
.RS 4
StoneyDSP (nathanjhood@googlemail.com)
.RE
.PP
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2023-08-24
.RE
.PP
\fBCopyright\fP
.RS 4
This file was generated by using Vector-of-Bool's excellent '\fBCMakeRC\fP' resource compiler script from CMake's template resources for Windows\&. The results have been given minimal tweaks - mostly just text formatting - to provide a similar interface to the rest of the project's codebase\&. Please see '\fBcmrc\&.hpp\fP' and Kitware\&.org for respective license information\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
