.TH "include/CxxWin/modules/Win32_core/system/win32_Toolchain.hpp" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_core/system/win32_Toolchain.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_WIN32_CORE_SYSTEM_TOOLCHAIN_HPP_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
StoneyDSP (nathanjhood@googlemail.com) 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2023-09-03
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define _WIN32_CORE_SYSTEM_TOOLCHAIN_HPP_"

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
