.TH "include/CxxWin/modules/Win32_core/window/win32_DPIScale.cpp" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_core/window/win32_DPIScale.cpp \- Contains the '\fBDPIScale\fP' class\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Contains the '\fBDPIScale\fP' class\&. 


.PP
\fBAuthor\fP
.RS 4
StoneyDSP (nathanjhood@googlemail.com)
.RE
.PP
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2023-08-25
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
