.TH "include/CxxWin/modules/Win32_core/memory/win32_SmartPointer.cpp" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_core/memory/win32_SmartPointer.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'win32_SmartPointer\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template<class ComClass > void \fBSafeRelease\fP (ComClass **ptr)"
.br
.RI "If the pointer is valid, call the underlying 'Release' method on it, and set it to 'nullptr'\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<class ComClass > void SafeRelease (ComClass ** ptr)"

.PP
If the pointer is valid, call the underlying 'Release' method on it, and set it to 'nullptr'\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIComClass\fP 
.RE
.PP
\fBParameters\fP
.RS 4
\fIptr\fP Accepts a pointer to a COM class or struct object\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
