.TH "include/CxxWin/modules/Win32_core/window/win32_MainWindow.hpp" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/modules/Win32_core/window/win32_MainWindow.hpp \- Contains a declaration of the '\fBMainWindow\fP' class which inherits from the '\fBBaseWindow\fP' class\&. Inherit this '\fBMainWindow\fP' class for a basic window functionality\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.RI "The '\fBMainWindow\fP' class\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_WIN32_MAINWINDOW_HPP_\fP"
.br
.RI "Contains a declaration of the '\fBMainWindow\fP' class which inherits from the '\fBBaseWindow\fP' class\&. "
.ti -1c
.RI "#define \fB_MainWindow_T\fP   \fBMainWindow\fP"
.br
.RI "The definition carrying the '\fBMainWindow\fP' datatype\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef class \fB_MainWindow_T\fP \fBMainWindow\fP"
.br
.RI "The '\fBMainWindow\fP' datatype\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains a declaration of the '\fBMainWindow\fP' class which inherits from the '\fBBaseWindow\fP' class\&. Inherit this '\fBMainWindow\fP' class for a basic window functionality\&. 


.PP
\fBAuthor\fP
.RS 4
StoneyDSP (nathanjhood@googlemail.com)
.RE
.PP
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2023-08-23
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define _MainWindow_T   \fBMainWindow\fP"

.PP
The definition carrying the '\fBMainWindow\fP' datatype\&. 
.SS "#define _WIN32_MAINWINDOW_HPP_"

.PP
Contains a declaration of the '\fBMainWindow\fP' class which inherits from the '\fBBaseWindow\fP' class\&. Inherit this '\fBMainWindow\fP' class for a basic window functionality\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef class \fB_MainWindow_T\fP \fBMainWindow\fP"

.PP
The '\fBMainWindow\fP' datatype\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
