.TH "Win32::Core::Native::UnicodeHandler" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Win32::Core::Native::UnicodeHandler
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <win32_Unicode\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "BOOL \fBSetVar\fP (HWND hwnd, LPCTSTR lpText)"
.br
.ti -1c
.RI "BOOL \fBSetVarA\fP (HWND hwnd, LPCSTR lpText)"
.br
.ti -1c
.RI "BOOL \fBSetVarW\fP (HWND hwnd, LPCWSTR lpText)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "BOOL Win32::Core::Native::UnicodeHandler::SetVar (HWND hwnd, LPCTSTR lpText)"

.SS "BOOL Win32::Core::Native::UnicodeHandler::SetVarA (HWND hwnd, LPCSTR lpText)"

.SS "BOOL Win32::Core::Native::UnicodeHandler::SetVarW (HWND hwnd, LPCWSTR lpText)"


.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
