.TH "include/CxxWin/WinMain.hpp" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/WinMain.hpp \- Contains the declarations of 'WinMain'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'MainComponent\&.hpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_WINMAIN_HPP_\fP"
.br
.RI "Contains the declarations of 'WinMain'\&. "
.ti -1c
.RI "#define \fBWinMain\fP   WinMain"
.br
.RI "Contains the ANSI-style declaration of 'WinMain'\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef LPSTR \fBLPCMDLINE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains the declarations of 'WinMain'\&. 


.PP
\fBAuthor\fP
.RS 4
StoneyDSP (nathanjhood@googlemail.com)
.RE
.PP
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2023-08-23
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define _WINMAIN_HPP_"

.PP
Contains the declarations of 'WinMain'\&. 
.SS "#define WinMain   WinMain"

.PP
Contains the ANSI-style declaration of 'WinMain'\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef LPSTR \fBLPCMDLINE\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
