.TH "include/CxxWin/WinMain.cpp" 3Version 1.0.1" "CxxWin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CxxWin/WinMain.cpp \- Contains the definitions of 'WinMain'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'WinMain\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int WINAPI \fBWinMain\fP (HINSTANCE hInstance, HINSTANCE hPrevInstance, \fBLPCMDLINE\fP lpCmdLine, int nShowCmd)"
.br
.RI "The main entry point for the runtime executable binary\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains the definitions of 'WinMain'\&. 


.PP
\fBAuthor\fP
.RS 4
StoneyDSP (nathanjhood@googlemail.com)
.RE
.PP
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2023-08-23
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int WINAPI WinMain (HINSTANCE hInstance, HINSTANCE hPrevInstance, \fBLPCMDLINE\fP lpCmdLine, int nShowCmd)"

.PP
The main entry point for the runtime executable binary\&. 
.PP
\fBParameters\fP
.RS 4
\fIhInstance\fP 
.br
\fIhPrevInstance\fP 
.br
\fIlpCmdLine\fP 
.br
\fInShowCmd\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CxxWin from the source code\&.
