/***************************************************************************//**
 * @file win32_SmallLogo_png.hpp
 * @author StoneyDSP (nathanjhood@googlemail.com)
 *
 * @brief Contains a default declaration of 'SmallLogo_png_array' (see
 * 'copyright' section).
 *
 * @version 1.0.0
 * @date 2023-08-24
 *
 * @copyright This file was generated by using Vector-of-Bool's excellent
 * 'CMakeRC' resource compiler script from CMake's template resources for
 * Windows. The results have been given minimal tweaks - mostly just text
 * formatting - to provide a similar interface to the rest of the project's
 * codebase. Please see 'cmrc.hpp' and Kitware.org for respective license
 * information.
 *
 * @see 'SmallLogo.png'
 *
 ******************************************************************************/
#pragma once

/**
 * @brief Contains a default declaration of 'SmallLogo_png_array' (see
 * 'copyright' section).
 *
 */
#define _WIN32_RESOURCE_IMG_SMALL_LOGO_PNG_H_

namespace
{
/** @brief An array of bytes representing 'Logo.png'. */
const char SmallLogo_png_array[168];
} // namespace

namespace CMakeRC::Img
{
/**
 * @namespace CMakeRC::Img::SmallLogo
 *
 * @brief The 'SmallLogo' namespace. Contains declarations and definitions
 * of binary-compiled 'SmallLogo.png' for interacting with Win32 API.
 *
 */
namespace SmallLogo
{
/** @brief Pointer to the Beginning of 'SmallLogo_png_array'.*/
extern const char* const SmallLogo_png_begin;
/** @brief Pointer to the end of 'SmallLogo_png_array'.*/
extern const char* const SmallLogo_png_end;
} // namespace SmallLogo
} // namespace CMakeRC::Img
